name: Build and deploy JAR app to Azure Web App - backend-springboot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code from the repository
      - uses: actions/checkout@v4

      # 2. Set up the Java environment (version 17 in this case)
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'

      # 3. Build the Spring Boot app using Maven (from the backend directory)
      - name: Build with Maven
        working-directory: ./backend  # Run Maven inside the backend folder
        run: mvn clean install

      # 4. Upload the JAR artifact for the deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: ./backend/target/*.jar  # Path to the JAR file created after build

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the build job

    steps:
      # 1. Download the JAR artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      # 2. Log in to Azure using service principal credentials
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 3. Deploy the JAR file to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backend-springboot'  # Name of the Azure Web App
          package: '*.jar'  # Deploy the JAR file
